version: "3.7"

services:
  db:
    image: mongo:4.2
    container_name: db_cat
    restart: always
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_DATABASE: cat
      MONGO_INITDB_ROOT_USERNAME: nodeauth
      MONGO_INITDB_ROOT_PASSWORD: nodeauth
